name: "Warren - .NET Migrations"
description: "Installs the dotnet ef global tool and applies migrations to the database"
branding:
  icon: "database"
  color: "red"
inputs:
  project-path:
    description: "The path for the project that holds the migrations folder"
    required: true
  startup-project-path:
    description: "The startup project of the application"
    required: true
  context:
    description: "The DbContext class name"
    required: true
  connection:
    description: "The connection string for the database to apply migrations"
    required: true

runs:
  using: composite
  steps:
    - name: Clear previous tools installation
      shell: bash
      run: dotnet tool uninstall --global dotnet-ef || true

    - name: Install dotnet ef tool
      shell: bash
      run: dotnet tool install --global dotnet-ef

    - name: Update database
      shell: bash
      env:
        PROJECT_PATH: ${{ inputs.project-path }}
        STARTUP_PROJECT_PATH: ${{ inputs.startup-project-path }}
        CONTEXT: ${{ inputs.context }}
        CONNECTION: ${{ inputs.connection }}
      run: |
        export PATH=$PATH:$HOME/.dotnet/tools
        . ~/.bashrc
        dotnet tool restore
        dotnet ef database update --verbose --project=$PROJECT_PATH --startup-project=$STARTUP_PROJECT_PATH --context $CONTEXT --connection $CONNECTION

    - name: Uninstall dotnet-ef tool
      shell: bash
      run: dotnet tool uninstall --global dotnet-ef
